### PR TITLE
Use length(sol.t) for plot timestep counts under RAT v4

### LINKED ISSUE #1335: Makie plotting extension does not work with SciMLBase v3 and OrdinaryDiffEq v7
**Describe the bug 🐞**

The Makie plot extension does not work.

**Minimal Reproducible Example 👇**

```julia
using OrdinaryDiffEq
using CairoMakie

function lorenz!(du, u, p, t)
    σ, ρ, β = p
    du[1] = σ * (u[2] - u[1])
    du[2] = u[1] * (ρ - u[3]) - u[2]
    du[3] = u[1] * u[2] - β * u[3]
end

u0 = [1.0, 0.0, 0.0]
p = (10.0, 28.0, 8/3)
tspan = (0.0, 100.0)

prob = ODEProblem(lorenz!, u0, tspan, p)

lines(sol)
```

**Error & Stacktrace ⚠️**

```julia
ERROR: BoundsError: attempt to access 1248-element Vector{Float64} at index [3744]
Stacktrace:
  [1] throw_boundserror(A::Vector{Float64}, I::Tuple{Int64})
    @ Base .\essentials.jl:15
  [2] getindex
    @ .\essentials.jl:919 [inlined]
  [3] diffeq_to_arrays(sol::ODESolution{…}, plot_analytic::Bool, denseplot::Bool, plotdensity::Int64, tspan::Nothing, vars::Vector{…}, tscale::Symbol, plotat::Nothing)
    @ SciMLBase C:\Users\hyzhou\.julia\packages\SciMLBase\2gk1o\src\solutions\solution_interface.jl:449
  [4] convert_arguments(PT::Type{…}, sol::ODESolution{…}; plot_analytic::Bool, denseplot::Makie.Automatic, plotdensity::Makie.Automatic, plotat::Nothing, tspan::Nothing, tscale::Symbol, vars::Nothing, idxs::Nothing, scatter_discretes::Bool)
    @ SciMLBaseMakieExt C:\Users\hyzhou\.julia\packages\SciMLBase\2gk1o\ext\SciMLBaseMakieExt.jl:147
  [5] convert_arguments(PT::Type{…}, sol::ODESolution{…})
    @ SciMLBaseMakieExt C:\Users\hyzhou\.julia\packages\SciMLBase\2gk1o\ext\SciMLBaseMakieExt.jl:41
  [6] _register_argument_conversions!(::Type{Lines}, attr::ComputePipeline.ComputeGraph, user_kw::Dict{Symbol, Any})
    @ Makie C:\Users\hyzhou\.julia\packages\Makie\p9K7f\src\compute-plots.jl:500
  [7] register_arguments!
    @ C:\Users\hyzhou\.julia\packages\Makie\p9K7f\src\compute-plots.jl:386 [inlined]
  [8] (Lines)(user_args::Tuple{ODESolution{…}}, user_attributes::Dict{Symbol, Any})
    @ Makie C:\Users\hyzhou\.julia\packages\Makie\p9K7f\src\compute-plots.jl:781
  [9] _create_plot(F::Function, attributes::Dict{…}, args::ODESolution{…})
    @ Makie C:\Users\hyzhou\.julia\packages\Makie\p9K7f\src\figureplotting.jl:334
 [10] #lines#55
    @ C:\Users\hyzhou\.julia\packages\Makie\p9K7f\src\recipes.jl:530 [inlined]
 [11] lines(args::ODESolution{…})
    @ Makie C:\Users\hyzhou\.julia\packages\Makie\p9K7f\src\recipes.jl:528
 [12] top-level scope
    @ REPL[36]:1
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
Status `C:\Users\hyzhou\Documents\GitHub\TestParticle.jl\docs\Project.toml`
  [13f3f980] CairoMakie v0.15.10
  [0ca39b1e] Chairmarks v1.3.1
  [459566f4] DiffEqCallbacks v4.17.0
  [3c3547ce] DiskArrays v0.4.19
  [0b91fe84] DisplayAs v0.1.6
  [31c24e10] Distributions v0.25.125
  [e30172f5] Documenter v1.17.0
  [4710194d] DocumenterVitepress v0.3.3
  [68837c9b] FHist v0.11.18
  [05065131] FieldTracer v0.2.1
  [f6369f11] ForwardDiff v1.3.3
  [5c1252a2] GeometryBasics v0.5.10
  [f67ccb44] HDF5 v0.17.3
  [a98d9a8b] Interpolations v0.16.2
  [033835bb] JLD2 v0.6.4
  [98b081ad] Literate v2.21.0
  [e551bd30] Magnetostatics v0.1.10
⌅ [eacbb407] Meshes v0.56.4
  [1dea7af3] OrdinaryDiffEq v7.0.0
  [43a3c2be] PairPlots v3.0.3
  [731186ca] RecursiveArrayTools v4.2.0
  [0bca4576] SciMLBase v3.6.0
  [276daf66] SpecialFunctions v2.7.2
  [90137ffa] StaticArrays v1.9.18
  [09ab397b] StructArrays v0.7.3
  [48a634ad] Tensors v1.17.0
  [953b605b] TestParticle v0.22.0 `.`
  [1986cc42] Unitful v1.28.0
  [63a0b508] VelocityDistributionFunctions v0.2.1
```

  - Output of `versioninfo()`

```julia
Julia Version 1.12.6
Commit 15346901f0 (2026-04-09 19:20 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 20 × Intel(R) Core(TM) Ultra 7 265K
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, arrowlake-s)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 20 virtual cores)
```

### PR DESCRIPTION
**Pull request by ChrisRackauckas-Claude**
Fixes #1335.

## Problem

Under RecursiveArrayTools v4 / SciMLBase v3, `length(sol::ODESolution)` is `prod(size(sol)) = state_dim * n_timesteps` (full AbstractArray length), not the timestep count. Three call sites in `src/solutions/solution_interface.jl` still assumed the old semantics:

| Line | Site | Effect |
|---|---|---|
| ~232-233 | `@recipe` `plotdensity` default | `100 * length(sol)` gave densities `state_dim`× larger than intended (mostly harmless but wrong) |
| ~423 | `diffeq_to_arrays`'s `end_idx` | The user-visible bug: `end_idx` ended up `state_dim * n_timesteps`, then `sol.t[end_idx]` blew up with `BoundsError: attempt to access N-element Vector{Float64} at index [3*N]` (1295/3885 in the issue) |

The bug surfaces through the Makie extension at `ext/SciMLBaseMakieExt.jl:147`'s `convert_arguments` call, which is what `lines(sol)` exercises.

## Fix

Replace the three `length(sol)` references in those plot-machinery contexts with `length(sol.t)` (the timestep count under both old and new RAT majors).

## Validation

End-to-end reproducer (post-fix passes; pre-fix throws the exact `BoundsError` from the issue):

```julia
using OrdinaryDiffEq, SciMLBase
prob = ODEProblem((du, u, p, t) -> (du[1] = u[2]; du[2] = -u[1]),
                  [1.0, 0.0], (0.0, 100.0))
sol = solve(prob, Tsit5())
vars = SciMLBase.interpret_vars(nothing, sol)
SciMLBase.diffeq_to_arrays(sol, false, true,
    max(1000, 10 * length(sol.t)),
    nothing, vars, :identity, nothing)
```

Returns `(plot_vecs, labels)` with the right shape (`2 × ~10·n_timesteps × n_series`).

### CODE REVIEW

File: test/downstream/plot_lines.jl [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+# `prod(size(sol)) = state_dim * n_timesteps`, not the timestep count.
+# Three call sites in `solution_interface.jl` were assuming the old
+# semantics, which broke both the `@recipe` Plots path and Makie's
+# `convert_arguments` on any multi-state ODE.
+#
+# `test/solution_interface.jl` already locks the `diffeq_to_arrays`
+# regression at the SciMLBase layer. This file exercises the actual
+# user-visible plotting paths through the Plots recipe and the Makie
+# extension, on the exact MWE from #1335 (Lorenz with `lines(sol)`).
+
```
Comment (ChrisRackauckas) [inline test/downstream/plot_lines.jl]:
```suggestion
```

File: test/downstream/plot_lines.jl [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+prob = ODEProblem(lorenz!, [1.0, 0.0, 0.0], (0.0, 100.0), (10.0, 28.0, 8 / 3))
+sol = solve(prob, Tsit5())
+# Precondition: the multi-state shape that exposes the bug.
+@assert length(sol) != length(sol.t)
+
+@testset "Plots recipe on multi-state ODESolution" begin
+    using Plots: Plots, plot
+    # Both the default-density path (no kwargs) and an explicit denseplot
+    # path go through the @recipe definition's `plotdensity` default,
+    # which used `length(sol)` instead of `length(sol.t)`.
```
Comment (ChrisRackauckas) [inline test/downstream/plot_lines.jl]:
```suggestion
```

File: test/downstream/plot_lines.jl [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+    σ, ρ, β = p
+    du[1] = σ * (u[2] - u[1])
+    du[2] = u[1] * (ρ - u[3]) - u[2]
+    du[3] = u[1] * u[2] - β * u[3]
+    return nothing
+end
+prob = ODEProblem(lorenz!, [1.0, 0.0, 0.0], (0.0, 100.0), (10.0, 28.0, 8 / 3))
+sol = solve(prob, Tsit5())
+# Precondition: the multi-state shape that exposes the bug.
+@assert length(sol) != length(sol.t)
```
Comment (ChrisRackauckas) [inline test/downstream/plot_lines.jl]:
```suggestion
```

File: test/downstream/plot_lines.jl [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+end
+
+@testset "Makie convert_arguments on multi-state ODESolution" begin
+    using Makie
+    # This is the path `lines(sol)` lowers to via the Makie extension's
+    # `SciMLBaseMakieExt.convert_arguments(::Type{Lines}, sol)`. No
+    # backend (CairoMakie/GLMakie) needed — argument conversion runs
+    # in core Makie and triggers the bug at `diffeq_to_arrays` time.
+    # The extension returns a `Vector{PlotSpec}` (one Lines per series);
+    # what matters here is that the call doesn't BoundsError.
```
Comment (ChrisRackauckas) [inline test/downstream/plot_lines.jl]:
```suggestion
```
