### PR TITLE
fix: fix plot recipe when single symbolic index is provided

### LINKED ISSUE #747: Plotting with a scalar symbol idx stopped working on 2.45 and 2.45.1
This previously worked but now errors
```julia
using Catalyst, OrdinaryDiffEq, Plots
rn = @reaction_network begin
       k, A --> ∅
       end
oprob = ODEProblem(rn, [rn.A => 10.0], (0.0, 10.0), [rn.k => 1.0])
sol = solve(oprob)
plot(sol, idxs = :A)
```
but now gives
```julia
ERROR: MethodError: no method matching iterate(::Symbol)

Closest candidates are:
  iterate(::DataStructures.SparseIntSet, Any...)
   @ DataStructures ~/.julia/packages/DataStructures/95DJa/src/sparse_int_set.jl:147
  iterate(::Core.Compiler.InstructionStream, ::Int64)
   @ Base show.jl:2778
  iterate(::Core.Compiler.InstructionStream)
   @ Base show.jl:2778
  ...

Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/SciMLBase/jh7eV/src/solutions/solution_interface.jl:181 [inlined]
 [2] apply_recipe(plotattributes::AbstractDict{Symbol, Any}, sol::SciMLBase.AbstractTimeseriesSolution)
   @ SciMLBase ~/.julia/packages/RecipesBase/BRe07/src/RecipesBase.jl:300
 [3] _process_userrecipes!(plt::Any, plotattributes::Any, args::Any)
   @ RecipesPipeline ~/.julia/packages/RecipesPipeline/BGM3l/src/user_recipe.jl:38
 [4] recipe_pipeline!(plt::Any, plotattributes::Any, args::Any)
   @ RecipesPipeline ~/.julia/packages/RecipesPipeline/BGM3l/src/RecipesPipeline.jl:72
 [5] _plot!(plt::Plots.Plot, plotattributes::Any, args::Any)
   @ Plots ~/.julia/packages/Plots/du2dt/src/plot.jl:223
 [6] plot(args::Any; kw...)
   @ Plots ~/.julia/packages/Plots/du2dt/src/plot.jl:102
 [7] top-level scope
   @ REPL[10]:1
```
Using `idxs = [:A]` works, but this has currently broken the Catalyst docs, where we previously used the scalar version in a number of places.

### PR DESCRIPTION
**Pull request by AayushSabharwal**
Close #747 

## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

File: test/downstream/integrator_indexing.jl [hunk 1]
```diff
@@ -318,14 +319,34 @@ integrator[lorenz2.x] = 2.0
...
+      [lorenz2.x,α],
+      [α],
+      [t,α],
+]
+      plot(sol; idxs)
+      if idxs isa Union{Tuple, AbstractArray}
+            idxs = map(idxs) do i
+                  hasname(i) ? getname(i) : i
+            end
+            if any(==(:t), idxs)
```
Comment (ChrisRackauckas) [inline test/downstream/integrator_indexing.jl:341]: what's up here?

**Review by ChrisRackauckas — APPROVED** [review]
